- dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
Updated authentication text as per JSPUI.
> LIBDRUM-385 Update authentication text

- dspace/config/dspace.cfg
Enabled administrators to login as other users.
https://issues.umd.edu/browse/LIBDRUM-392
> LIBDRUM-392. Enable "Login as E-Person" button

- dspace/config/modules/workflow.cfg
Bitstream data can now be edited along with other metadata in the workflow process.
https://issues.umd.edu/browse/LIBDRUM-355
> LIBDRUM-355. Implement "Submission" feature in XMLUI

- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/cocoon/BitstreamReader.java
Fixing bug introduced by LIBDRUM-344 changes.
https://issues.umd.edu/browse/LIBDRUM-395
> LIBDRUM-395. Blank documents on new submissions.

- dspace-xmlui/src/main/java/org/dspace/app/xmlui/cocoon/ConcatenationReader.java
- dspace-xmlui/src/main/java/org/dspace/app/xmlui/cocoon/SafeResourceReader.java
- dspace-xmlui/src/main/webapp/sitemap.xmap
Applied patch for XMLUI fix as per issue.
https://issues.umd.edu/browse/LIBDRUM-369
> LIBDRUM-369. Patch XMLUI with fixes for Security Advisory

- dspace-xmlui-mirage2/src/main/webapp/sitemap.xmap
- dspace-xmlui-mirage2/src/main/webapp/styles/shared/_dspace-bootstrap-tweaks.scss
- dspace-xmlui/src/main/webapp/exception2dri.xslt
- dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
Updated the Mirage2 theme files as per the issue here: https://jira.duraspace.org/browse/DS-1596
https://issues.umd.edu/browse/LIBDRUM-393
> LIBDRUM-393 Page not found look and feel

- dspace/modules/additions/src/main/java/org/dspace/content/Collection.java
https://issues.umd.edu/browse/LIBDRUM-402
> LIBDRUM-402. Error message when deleting an item.

- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/artifactbrowser/RestrictedItem.java
Clear embargo messages from session after displaying.
https://issues.umd.edu/browse/LIBDRUM-397
> LIBDRUM-397. Clicking on embargoed document takes you to login screen

- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/eperson/EditProfile.java
Error resolved. Sign up process working.
https://issues.umd.edu/browse/LIBDRUM-401
> LIBDRUM-401. Error when registering as a new user

- dspace/modules/additions/src/main/java/org/dspace/authenticate/CASAuthentication.java
Fixed the Exception.
https://issues.umd.edu/browse/LIBDRUM-414
> LIBDRUM-414 Fix Nullpointerexception in logs related to LIBDRUM-350

- dspace-xmlui-mirage2/src/main/webapp/xsl/preprocess/general.xsl
- dspace/config/news-xmlui.xml
- dspace/config/pages/about
- dspace/config/pages/about-submitting
- dspace/config/pages/license-text
- dspace/config/pages/permission-letter
- dspace/config/pages/scope-of-drum-content
- dspace/config/pages/statistics
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/navigation.xsl
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/page-structure.xsl
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/preprocess/general.xsl
https://issues.umd.edu/browse/LIBDRUM-416
> Feature/libdrum 416: migrate html content to XMLUI.

- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/aspect/artifactbrowser/item-view.xsl
- dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
https://issues.umd.edu/browse/LIBDRUM-407
> LIBDRUM-407. Add fields to Simple Item Record view.

- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/DescribeStep.java
The "Subject Categories" link has been removed.
https://issues.umd.edu/browse/LIBDRUM-412
> LIBDRUM-412. Remove Subject Categories link from submission page

- dspace-xmlui/src/main/resources/aspects/Administrative/administrative.js
Pulling in core bug fix for https://jira.duraspace.org/browse/DS-1447
https://issues.umd.edu/browse/LIBDRUM-350
> DS-1447 Login as User redirecting to wrong page

- dspace/modules/xmlui/src/main/resources/aspects/Administrative/administrative.js
Copied DS-1447 patch to local customization.
https://issues.umd.edu/browse/LIBDRUM-350
> LIBDRUM-350. Implement "LDAP Authorization" feature in XMLUI.

- dspace/config/dspace.cfg
https://issues.umd.edu/browse/LIBDRUM-427
> LIBDRUM-427. Setup Google Analytics for DRUM XMLUI.

- dspace/modules/xmlui/src/main/java/edu/umd/lib/dspace/app/xmlui/aspect/artifactbrowser/EmbargoListHelper.java
Updated the query to match the schema changes in dspace 5.
Removed hard coded references to metadata field ids.
Added resource type id to get the correct title.
https://issues.umd.edu/browse/LIBDRUM-441
> LIBDRUM-441. Embargo list page does not work.

- dspace/modules/additions/src/main/java/org/dspace/content/Collection.java
Bug introduced during the upgrade.
https://issues.umd.edu/browse/LIBDRUM-443
> LIBDRUM-443. Error message when creating new Collection.

- dspace/config/input-forms.xml
Restored UMD changes removed during the upgrade.
Lost commits:
https://github.com/umd-lib/drum/commit/5bd693be58b493f2014c8918ddc35aeba9da6f51
https://github.com/umd-lib/drum/commit/7c31d746ef3a860ab022fa495cfa2fa3d5259f4d
https://issues.umd.edu/browse/LIBDRUM-432
> LIBDRUM-432. Verify input-forms change does not affect drum.

- dspace/modules/additions/src/main/java/org/dspace/content/Collection.java
Updated SQL query in UMD custom code to match dspace 5.4 schema changes.
https://issues.umd.edu/browse/LIBDRUM-448
> LIBDRUM-448. Error message when creating new ETD Department.

- dspace/modules/xmlui/src/main/java/edu/umd/lib/dspace/app/xmlui/aspect/administrative/units/EditUnitsForm.java
Added condition to check unit not null before accessing it.
https://issues.umd.edu/browse/LIBDRUM-449
> LIBDRUM-449. Error when creating new Unit.

- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/objectmanager/ItemAdapter.java
Switched from database to solr statistics as the source of the view count.
https://issues.umd.edu/browse/LIBDRUM-450
> LIBDRUM-450. Number of downloads not updating in records.

- dspace/bin/import-setup.sh
https://issues.umd.edu/browse/LIBDRUM-459
> LIBDRUM-459. Add import-setup.sh script to DRUM.

- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/objectmanager/ItemAdapter.java
Multiple bitstream count fix.
https://issues.umd.edu/browse/LIBDRUM-460
> LIBDRUM-460. DRUM stats not updating properly.

- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/styles/classic_mirage_color_scheme/_general.scss
https://issues.umd.edu/browse/LIBDRUM-423
> LIBDRUM-423. Remove dark border around library and drum banner.

- dspace/config/launcher.xml
- dspace/config/log4j.properties
- dspace/config/modules/stats.cfg
- dspace/config/spring/jspui/open-url-listeners.xml
- dspace/config/spring/xmlui/open-url-listeners.xml
- dspace/modules/atmire-statistics-exporter/atmire-statistics-exporter-api/pom.xml
- dspace/modules/atmire-statistics-exporter/atmire-statistics-exporter-api/src/main/java/com/atmire/statistics/export/ExportUsageEventListener.java
- dspace/modules/atmire-statistics-exporter/atmire-statistics-exporter-api/src/main/java/com/atmire/statistics/export/OpenUrlTrackerLogger.java
- dspace/modules/atmire-statistics-exporter/atmire-statistics-exporter-api/src/main/java/com/atmire/statistics/export/RetryOpenUrlTracker.java
- dspace/modules/atmire-statistics-exporter/atmire-statistics-exporter-api/src/main/java/org/dspace/core/ConfigurationManager.java
- dspace/modules/atmire-statistics-exporter/atmire-statistics-exporter-api/src/main/java/org/dspace/statistics/util/SpiderDetector.java
- dspace/modules/atmire-statistics-exporter/atmire-statistics-exporter-api/src/main/java/org/dspace/usage/AbstractUsageEventListener.java
- dspace/modules/atmire-statistics-exporter/atmire-statistics-exporter-api/src/main/java/storage/rdbms/DatabaseRegistryUpdater.java
- dspace/modules/atmire-statistics-exporter/atmire-statistics-exporter-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/oracle/V5.0_2015.06.18__statistics-harvester.sql
- dspace/modules/atmire-statistics-exporter/atmire-statistics-exporter-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/V5.0_2015.06.18__statistics-harvester.sql
- dspace/modules/atmire-statistics-exporter/pom.xml
- dspace/modules/jspui/pom.xml
- dspace/modules/pom.xml
- dspace/modules/xmlui/pom.xml
- dspace/pom.xml
- dspace/src/main/config/build.xml
- local.properties
- local.properties.template
https://issues.umd.edu/browse/LIBDRUM-488
> LIBDRUM-488. Install IRUS-UK patch.

- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/app/EtdLoader.java
https://issues.umd.edu/browse/LIBDRUM-89
> LIBDRUM-89. attach Proquest ETD metadata to Item as a hidden Bitstream.

- dspace/config/modules/stats.cfg
https://issues.umd.edu/browse/LIBDRUM-488
> LIBDRUM-488. Updated tracker url for production.

- dspace/modules/additions/src/main/java/org/dspace/workflow/WorkflowManager.java
https://issues.umd.edu/browse/LIBDRUM-493
> LIBDRUM-493. Fixed a patch problem that added arguments to email twice.

- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/page-structure.xsl
https://issues.umd.edu/browse/LIBDRUM-506
> LIBDRUM-506. Add accessibility url to footer.

- dspace/modules/additions/src/main/java/org/dspace/content/CollectionServiceImpl.java
- dspace/modules/additions/src/main/java/org/dspace/content/EtdUnitServiceImpl.java
- dspace/modules/additions/src/main/java/org/dspace/content/dao/impl/CollectionDAOImpl.java
- dspace/modules/additions/src/main/java/org/dspace/eperson/UnitServiceImpl.java
- dspace/modules/xmlui/src/main/java/edu/umd/lib/dspace/app/xmlui/aspect/administrative/FlowETDDepartmentUtils.java
- dspace/modules/xmlui/src/main/java/edu/umd/lib/dspace/app/xmlui/aspect/administrative/etd_departments/EditETDDepartmentsForm.java
- dspace/modules/xmlui/src/main/java/edu/umd/lib/dspace/app/xmlui/aspect/administrative/etd_departments/ManageETDDepartmentsMain.java
- dspace/modules/xmlui/src/main/java/edu/umd/lib/dspace/app/xmlui/aspect/administrative/units/EditUnitsForm.java
- dspace/modules/xmlui/src/main/resources/aspects/Administrative/administrative.js
https://issues.umd.edu/browse/LIBDRUM-521
> LIBDRUM-521. ETD Departments page not working

- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/content/EmbargoDTO.java
- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/content/EmbargoDTOServiceImpl.java
- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/content/dao/EmbargoDTODAO.java
- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/content/dao/impl/EmbargoDTODAOImpl.java
- dspace/modules/xmlui/src/main/java/edu/umd/lib/dspace/app/xmlui/aspect/artifactbrowser/EmbargoListDisplay.java
- dspace/modules/xmlui/src/main/java/edu/umd/lib/dspace/app/xmlui/aspect/artifactbrowser/EmbargoListDownloader.java
https://issues.umd.edu/browse/LIBDRUM-522
> LIBDRUM-522. Fixed Embargo List page issues.

- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/content/EmbargoDTO.java
- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/content/EmbargoDTOServiceImpl.java
- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/content/dao/EmbargoDTODAO.java
- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/content/dao/impl/EmbargoDTODAOImpl.java
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/page-structure.xsl
- dspace/modules/xmlui/src/main/java/edu/umd/lib/dspace/app/xmlui/aspect/artifactbrowser/EmbargoListDisplay.java
- dspace/modules/xmlui/src/main/java/edu/umd/lib/dspace/app/xmlui/aspect/artifactbrowser/EmbargoListDownloader.java
https://issues.umd.edu/browse/LIBDRUM-508
> LIBDRUM-508. Update UMD Banner.

- dspace/config/crosswalks/DIM2UmdDataCite.xsl
- dspace/config/dspace.cfg
- dspace/config/spring/api/identifier-service.xml
- dspace/modules/additions/src/main/java/org/dspace/content/WorkspaceItem.java
- dspace/modules/additions/src/main/java/org/dspace/workflowbasic/BasicWorkflowItem.java
https://issues.umd.edu/browse/LIBDRUM-524
> LIBDRUM-524. Submissions not being accepted into collections.

- README.md
- dspace/pom.xml
https://issues.umd.edu/browse/LIBDRUM-514
> LIBDRUM-514. Added maven profiles for Nexus deployment.

- README.md
- dspace/config/dspace.cfg
- dspace/pom.xml
https://issues.umd.edu/browse/LIBDRUM-481
> LIBDRUM-481. Disable "Request a Copy" feature.

- README.md
- dspace/config/dspace.cfg
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/aspect/artifactbrowser/item-view.xsl
- dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
- dspace/pom.xml
https://issues.umd.edu/browse/LIBDRUM-505
> LIBDRUM-505. Show dc.rights field to Simple Item Record Display

- README.md
- dspace/config/dspace.cfg
- dspace/config/local.cfg.TEMPLATE
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/aspect/artifactbrowser/item-view.xsl
- dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
- dspace/pom.xml
https://issues.umd.edu/browse/LIBDRUM-532
> LIBDRUM-532. Update environment configuration template file.

- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/submit/step/LibraryAwardUploadStep.java
- dspace/modules/xmlui/src/main/java/edu/umd/lib/dspace/app/xmlui/aspect/submission/submit/XMLUILibraryAwardUploadStep.java
Cannot upload files for the Library Award for Undergraduate Research submission process.
- Reimplemented the Library Award classes based on DSpace 6 version.
https://issues.umd.edu/browse/LIBDRUM-535
> LIBDRUM-535. Cannot upload files for the Library Award.

- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/objectmanager/ItemAdapter.java
https://issues.umd.edu/browse/LIBDRUM-537
> LIBDRUM-537. Include legacy ID in statistics search.

- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/app/CissmLoader.java
- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/app/EtdLoader.java
- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/app/GetCollectionId.java
- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/app/cleanup/DeleteItems.java
- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/app/cleanup/EtdMangledDates.java
- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/app/isr/Loader.java
https://issues.umd.edu/browse/LIBDRUM-541
> LIBDRUM-541. Replace ignoreAuthorization with turnOffAuthorisationSystem

- dspace/config/dspace.cfg
https://issues.umd.edu/browse/LIBDRUM-539
> LIBDRUM-539. Re-enable useProxies configuration.

- dspace/config/dspace.cfg
https://issues.umd.edu/browse/LIBDRUM-548
> LIBDRUM-548. Update ETD collection uuid in dspace.cfg

- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/authenticate/Ldap.java
https://issues.umd.edu/browse/LIBDRUM-549
> LIBDRUM-549. New registered DRUM users cannot login.

- dspace/config/dspace.cfg
- dspace/config/local.cfg.TEMPLATE
https://issues.umd.edu/browse/LIBDRUM-475
> LIBDRUM-475. Enable ORCID Authority Control.

- dspace/config/load/etd2dc.xsl
- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/app/EtdLoader.java
https://issues.umd.edu/browse/LIBDRUM-552
> LIBDRUM-552. Add ORCID id to author authority control in ETDLoader.

- dspace/modules/additions/src/main/java/org/dspace/content/crosswalk/XHTMLHeadDisseminationCrosswalk.java
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/aspect/artifactbrowser/item-view.xsl
https://issues.umd.edu/browse/LIBDRUM-565
> LIBDRUM-565. Display DOI as Link on the item view.

- dspace/config/dspace.cfg
- dspace/config/local.cfg.TEMPLATE
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/page-structure.xsl
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/artifactbrowser/FeedbackForm.java
https://issues.umd.edu/browse/LIBDRUM-563
> LIBDRUM-563. Use Wufoo form for collecting feedback.

- dspace/config/xmlui.xconf
- dspace/modules/xmlui/src/main/resources/aspects/Feedback/sitemap.xmap
- dspace/modules/xmlui/src/main/resources/aspects/ViewArtifacts/sitemap.xmap
- Enable the Feedback aspect in xmlui.xconf
- Remove the "feedback" pattern matching from ViewArtifacts aspect.
- Add noncaching type to Feedback aspect pipeline.
https://issues.umd.edu/browse/LIBDRUM-563
> LIBDRUM-563. Disable caching for feedback aspect.

- dspace/modules/additions/src/main/java/org/dspace/identifier/DOI.java
https://issues.umd.edu/browse/LIBDRUM-571
> LIBDRUM-571. Update DOI base URL.

- dspace/config/crosswalks/DIM2UmdDataCite.xsl
https://issues.umd.edu/browse/LIBDRUM-573
> LIBDRUM-573. Update Datacite crosswalk resource type mapping.

- dspace/config/item-submission.xml
- dspace/modules/additions/src/main/java/org/dspace/submit/AbstractProcessingStep.java
- dspace/modules/additions/src/main/java/org/dspace/submit/step/ConditionalLicenseStep.java
- dspace/modules/additions/src/main/java/org/dspace/submit/step/OptionalUploadStep.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/AbstractStep.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/OptionalUploadStep.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/UploadStep.java
- dspace/modules/xmlui/src/main/resources/aspects/Submission/submission.js
- File upload is made optional
- The License step is included only if there is a file upload.
https://issues.umd.edu/browse/LIBDRUM-581
> LIBDRUM-581. MHHEA Submission Workflow.

- dspace/config/input-forms.xml
- dspace/config/item-submission.xml
- dspace/modules/additions/src/main/java/org/dspace/submit/AbstractProcessingStep.java
- dspace/modules/additions/src/main/java/org/dspace/submit/step/ConditionalLicenseStep.java
- dspace/modules/additions/src/main/java/org/dspace/submit/step/DescribeStep.java
- dspace/modules/additions/src/main/java/org/dspace/submit/step/OptionalUploadStep.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/AbstractStep.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/DescribeStep.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/OptionalUploadStep.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/UploadStep.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/wing/element/Field.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/wing/element/Text.java
- dspace/modules/xmlui/src/main/resources/aspects/Submission/submission.js
https://issues.umd.edu/browse/LIBDRUM-582
> LIBDRUM-582. Add external links field to MHHEA submission form.

- dspace/config/input-forms.xml
- dspace/config/item-submission.xml
- dspace/modules/additions/src/main/java/org/dspace/submit/AbstractProcessingStep.java
- dspace/modules/additions/src/main/java/org/dspace/submit/step/ConditionalLicenseStep.java
- dspace/modules/additions/src/main/java/org/dspace/submit/step/DescribeStep.java
- dspace/modules/additions/src/main/java/org/dspace/submit/step/OptionalUploadStep.java
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/styles/_style.scss
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/aspect/artifactbrowser/item-view.xsl
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/AbstractStep.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/DescribeStep.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/OptionalUploadStep.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/UploadStep.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/wing/element/Field.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/wing/element/Text.java
- dspace/modules/xmlui/src/main/resources/aspects/Submission/submission.js
- dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
- Show External Link field in left pane
- Show Notes (description) in righ pane
- Make all labels bold
https://issues.umd.edu/browse/LIBDRUM-583
> LIBDRUM-583. Item summary view customization.

- dspace/modules/additions/src/main/java/org/dspace/app/util/GoogleBitstreamComparator.java
https://issues.umd.edu/browse/LIBDRUM-587
> LIBDRUM-587. Fix comparator bug.

- dspace-rest/src/main/webapp/WEB-INF/web.xml
https://issues.umd.edu/browse/LIBDRUM-589
> LIBDRUM-589. Fix rest endpoint redirecting to port 8443

- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/administrative/FlowContainerUtils.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/administrative/community/EditCommunityMetadataForm.java
The community-group dropdown in the edit interface was not automatically selecting the community-group associated with community.
https://issues.umd.edu/browse/LIBDRUM-593
> LIBDRUM-593. Fix Community Group change on Community edit.

- dspace-xmlui-mirage2/src/main/webapp/xsl/core/elements.xsl
- dspace/modules/xmlui-mirage2/pom.xml
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/aspect/artifactbrowser/item-view.xsl
https://issues.umd.edu/browse/LIBDRUM-618
> LIBDRUM-618. Set h1 for first heading.

- dspace/modules/additions/src/main/resources/Messages.properties
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/styles/_style.scss
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/aspect/artifactbrowser/item-view.xsl
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/page-structure.xsl
- dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
https://issues.umd.edu/browse/LIBDRUM-617
> LIBDRUM-617. Replace <i> tag.

- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/styles/_style.scss
https://issues.umd.edu/browse/LIBDRUM-615
> LIBDRUM-615. Improve color contrast for links.

- dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/discovery/CollectionSearch.java
- dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/discovery/CommunitySearch.java
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/forms.xsl
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/navigation.xsl
- dspace/modules/xmlui/src/main/webapp/i18n/messages.xml
https://issues.umd.edu/browse/LIBDRUM-614
> LIBDRUM-614. Add labels for search field. 

- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/navigation.xsl
https://issues.umd.edu/browse/LIBDRUM-616
> LIBDRUM-616. Grouped radio buttons.

- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/page-structure.xsl
https://issues.umd.edu/browse/LIBDRUM-620
> LIBDRUM-620. Use specific HTML5 tags instead of div.

- dspace/config/modules/stats.cfg
https://issues.umd.edu/browse/LIBDRUM-605
> LIBDRUM-605. Update IRUS-USA endpoint URL

- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/page-structure.xsl
Also, added aria-label to distinguish nav sections.
https://issues.umd.edu/browse/LIBDRUM-620
> LIBDRUM-620. Reverted nav to div tag.

- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/aspect/artifactbrowser/browse.xsl
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/aspect/discovery/discovery.xsl
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/attribute-handlers.xsl
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/forms.xsl
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/utils.xsl
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/preprocess/browse.xsl
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/artifactbrowser/ConfigurableBrowse.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/discovery/SimpleSearch.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/wing/element/Field.java
- dspace/modules/xmlui/src/main/resources/aspects/Discovery/i18n/messages.xml
https://issues.umd.edu/browse/LIBDRUM-614
> LIBDRUM-614. More missing labels fix. 

- README.md
- dspace/src/main/docker/dspace-postgres-pgcrypto/Dockerfile
- dspace/src/main/docker/dspace-postgres-pgcrypto/install-pgcrypto.sh
https://issues.umd.edu/browse/LIBDRUM-622
> LIBDRUM-622. Docker configuration for drum postgres image

- dspace/config/dspace.cfg
- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/authenticate/Ldap.java
- dspace/modules/additions/src/main/java/org/dspace/authenticate/CASAuthentication.java
https://issues.umd.edu/browse/LIBDRUM-627
> LIBDRUM-627. Improve DRUM LDAP connection mechanism

- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/aspect/artifactbrowser/item-view.xsl
- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/utils.xsl
https://issues.umd.edu/browse/LIBDRUM-632
> LIBDRUM-632. Escape quotes on structured data json

- .dockerignore
- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- Dockerfile
- Dockerfile.ant
- Dockerfile.cli.jdk8
- Dockerfile.dependencies
- Dockerfile.dev
- Dockerfile.jdk8
- Dockerfile.jdk8-test
- Dockerfile.tomcat
- README.md
- docker-compose.yml
- dspace/config/log4j.properties
- dspace/modules/pom.xml
- dspace/modules/xmlui-mirage2/pom.xml
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/aspect/eperson/CASAuthenticateAction.java
- dspace/solr/Dockerfile
- dspace/solr/search/conf/solrconfig.xml
- dspace/solr/statistics/conf/solrconfig.xml
- dspace/src/main/docker-compose/README.md
- dspace/src/main/docker-compose/cli.ingest.yml
- dspace/src/main/docker-compose/local.cfg
- dspace/src/main/docker-compose/xmlui.xconf
- dspace/src/main/docker/README.md
- dspace/src/main/docker/dspace-postgres-pgcrypto/install-pgcrypto.sh
- dspace/src/main/docker/local.cfg
- dspace/src/main/docker/mvn-settings.xml
- postgres-init/README.md
- Added Dockerfiles to build images for local & k8s deployment.
- Added docker-compose for development environment setup.
- Added/updated DRUM configuration/scripts to run in dockerized environment.
https://issues.umd.edu/browse/LIBDRUM-622
> LIBDRUM-622. Dockerize DRUM.

- Dockerfile
- dspace/bin/load-etd-nightly
- dspace/bin/mail
https://issues.umd.edu/browse/LIBDRUM-622
> LIBDRUM-622. Fixes for ETD Loader.

- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/utils/AuthenticationUtil.java
- dspace/modules/xmlui/src/main/java/org/dspace/app/xmlui/utils/ContextUtil.java
https://issues.umd.edu/browse/LIBDRUM-640
> LIBDRUM-640. FIx reverse proxy IP. 

- dspace/config/dspace.cfg
https://issues.umd.edu/browse/LIBDRUM-643
> LIBDRUM-643. Use HTTPS url for cc license.

- dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/core/page-structure.xsl
https://issues.umd.edu/browse/LIBDRUM-646
> LIBDRUM-646. Fix static pages path.

- .vscode/launch.json
- Dockerfile.dev-additions
- Dockerfile.dev-base
- docker-compose.yml
- dspace/docs/DRUM7DBRestore.md
- dspace/docs/Drum7DockerDevelopmentEnvironment.md
- Add quick build instructions and Dockerfiles.
- Enable debug configuration to docker-compose
- Update vscode debug configuration for the project.
- Eliminate the need to build a separte cli image.
https://issues.umd.edu/browse/LIBDRUM-649
* First, ...
* Second, ...
**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new …
> LIBDRUM-649. Improve development process.

- dspace/modules/additions/src/main/java/org/dspace/content/Community.java
- dspace/modules/server/src/main/java/org/dspace/app/rest/CommunityCommunityGroupController.java
- dspace/modules/server/src/main/java/org/dspace/app/rest/model/CommunityRest.java
- dspace/modules/server/src/main/java/org/dspace/app/rest/repository/CommunityCommunityGroupLinkRepository.java
- dspace/modules/server/src/test/java/org/dspace/app/rest/CommunityCommunityGroupControllerIT.java
https://issues.umd.edu/browse/LIBDRUM-664
> LIBDRUM-701. Add API endpoints to GET/PUT community group of a community.

- dspace/modules/additions/src/main/java/org/dspace/content/InProgressSubmission.java
- dspace/modules/additions/src/main/java/org/dspace/content/WorkspaceItem.java
- dspace/modules/additions/src/main/java/org/dspace/xmlworkflow/storedcomponents/XmlWorkflowItem.java
In LIBDRUM-511, additional methods were added to the "InProgressSubmission" interface which was causing the stock DSpace "XmlWorkflowItem" implementation to fail. A UMD-customized version of the "XmlWorkflowItem" class (in the "additions" module) which has "stub" implementations of the methods has been restored.
The UMD-customized "InProgressSubmission" interface was also modified in LIBDRUM-628, to support the Data Community workflow, which has not yet been implemented in DSpace 7 (see LIBDRUM-682).
Since it is not clear whether the implementation of the Data Community workflow will actually require the methods added in LIBDRUM-628, in this issue the methods in the "nProgressSubmission" interface (and their implementations in the "WorkspaceItem" and "XmlWorkflowItem" classes) were …
> LIBDRUM-716. Restore UMD-customized XmlWorkflowItem class

- Dockerfile.ci
- Jenkinsfile
Initial Dockerfile.ci/Jenkinsfile implementation for running
DSpace unit and integration tests.
Static analysis checking is currently disabled, because
DSpace is set up to fail the build if there are any CheckStyle
violations, and we are currently not attempting to
fix Checkstyle errors. See LIBDRUM-667.
https://umd-dit.atlassian.net/browse/LIBDRUM-731
* First, ...
* Second, ...
**Include guidance for …
> LIBDRUM-731. Initial Dockerfile.ci/Jenkinsfile implementation

- dspace/config/local.cfg.EXAMPLE
Modified the "local.cfg.EXAMPLE" file to "expose" the "dspace.name" and "dspace.baseUrl" properties, i.e. allow them to be retrieved by the Angular front-end via the "properties" REST endpoint.
These properties are used by the “JsonLdWebsiteComponent” for populating the "WebSite" JSON-LD object.
https://umd-dit.atlassian.net/browse/LIBDRUM-715
* First, ...
* Second, ...
**Include guidance for how to …
> LIBDRUM-715. Modified "local.cfg.EXAMPLE" to expose config properties

- dspace/config/local.cfg.EXAMPLE
- dspace/config/modules/rest.cfg
The "rest.properties.exposed" properties in the "local.cfg" files were intended to be "additive" to the other properties in “dspace/config/modules/rest.cfg” file.
However, due to the way Apache Commons Configuration works when including files, these properties were actually completely overriding the entries in “dspace/config/modules/rest.cfg” file, so they are being removed.
Added the entries to the "dspace/config/modules/rest.cfg" file, and removed them from "dspace/config/local.cfg.EXAMPLE".
https://umd-dit.atlassian.net/browse/LIBDRUM-764
Please add a more detailed description of …
> LIBDRUM-764. Removed "rest.properties.exposed" props from local.cfg

- dspace/config/emails/subscription
Fixed a typo that was preventing the Subject line from being used in the email that is sent notifying subscribers of new items.
https://umd-dit.atlassian.net/browse/LIBDRUM-770
* First, ...
* Second, ...
**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 
_This checklist …
> LIBDRUM-770. Fixed Subject line for "subscription" email template

- dspace/docs/DrumCronTasks.md
Added documentation regarding DRUM cron tasks.
Placing in the "umd-lib/dspace" repository, instead of in "umd-lib/k8s-drum", since this seemed like the most likely place someone would look first, as the repository contains other DRUM customization information.
https://umd-dit.atlassian.net/browse/LIBDRUM-720
* First, ...
* Second, ...
**Include guidance for how to test or review your PR.** This may …
> LIBDRUM-720. Added "DrumCronTasks.md" file

- .github/workflows/build.yml
- Jenkinsfile
The license violations that were previously being reported appear to have been fixed. CheckStyle warnings were fixed as part of LIBDRUM=667.
Modified the GitHub Action ".github/workflows/build.yml" file to restore running both the license and CheckStyle checks.
Modified the "Jenkinsfile" using by Jenkins to restore the license checks (CheckStyle checking had previously been restored).
https://umd-dit.atlassian.net/browse/LIBDRUM-668
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to …
> LIBDRUM-668. Restored license and CheckStyle checks in CI jobs

- dspace/config/spring/api/identifier-service.xml
https://umd-dit.atlassian.net/browse/LIBDRUM-848
> LIBDRUM-848. Disable doi-filter.

- dspace/modules/additions/src/main/java/edu/umd/lib/dspace/authenticate/impl/Ldap.java
- dspace/modules/additions/src/test/java/edu/umd/lib/dspace/authenticate/impl/LdapTest.java
Updates DRUM based on DSpace 7.6.2 with the
LDAP modifications needed for the Workday transition on
November 15, 2024.
Note: There is a separate pull request #232 for DRUM based on
DSpace 7.6.1. Either or both of these pull request may be
merged, based on the timing of the DSpace 7.6.2 release.
https://umd-dit.atlassian.net/browse/LIBDRUM-750
> LIBDRUM-750. Updated LDAP for Workday transition
