dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/aspect/artifactbrowser/item-view.xsl
Filename now displaying when description not present.
https://issues.umd.edu/browse/LIBDRUM-404
=> LIBDRUM-404 Filename not displaying in Simple Item record display

dspace-xmlui-mirage2/src/main/webapp/xsl/preprocess/general.xsl, dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/preprocess/general.xsl
Reverted dspace-xmlui-mirage2 general.xsl to original state.
Updated xmlui-mirage2 module general.xsl with the customization.
https://issues.umd.edu/browse/LIBDRUM-416
=> LIBDRUM-416. migrate html content to XMLUI.

dspace/modules/xmlui-mirage2/src/main/webapp/themes/Mirage2/xsl/preprocess/communitylist.xsl
Applied change to community-browser-umd (previously applied only to community-browser-dept)
https://issues.umd.edu/browse/LIBDRUM-435
=> LIBDRUM-435. Update overlay classes with changes from dspace-5.4.

dspace/config/load/etd2dc.xsl
https://issues.umd.edu/browse/LIBDRUM-492
=> LIBDRUM-492. Match DISS_keyword node only if text non empty.

dspace/modules/additions/src/main/java/edu/umd/lib/dspace/app/EtdLoader.java
This bug was discovered when testing LIBDRUM-485, though not directly related to it.
https://issues.umd.edu/browse/LIBDRUM-485
=> LIBDRUM-485. Fix for array out of bound exception.

dspace/modules/additions/src/main/java/edu/umd/lib/dspace/authenticate/Ldap.java
The unit.getGroups now return a List object, so the Array.asList was creating a List within List.
https://issues.umd.edu/browse/LIBDRUM-525
=> LIBDRUM-525. Fixed Ldap bug.

dspace-api/src/main/java/org/dspace/app/itemimport/ItemImportServiceImpl.java
if any error occurs during a batch import, even the prior items in the batch that were loaded without error will not be commited due to transaction rollback.
This fix adds transaction commit after each item load.
https://issues.umd.edu/browse/LIBDRUM-566
=> LIBDRUM-566. Fix batch import issue.

dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java
DS-3969 Added check for null during indexing of OAI to avoid NullPointer
https://issues.umd.edu/browse/LIBDRUM-578
=> LIBDRUM-578. OAI indexing fails on DRUM

dspace/modules/additions/src/main/java/org/dspace/identifier/doi/DataCiteConnector.java
https://issues.umd.edu/browse/LIBDRUM-574
=> LIBDRUM-574. Log Datacite XML on HTTP 422 failure response.

dspace/modules/additions/src/main/java/org/dspace/identifier/DOIIdentifierProvider.java, dspace/modules/additions/src/main/java/org/dspace/identifier/doi/DataCiteConnector.java
Notes:
- DataCite MDS API changes (Eventual Consistency for read) is affecting the DOI regsitration.
- Check for reserved status are returning false even though reservation has succeeded.
- We can skip reservation status check - if we just reserved and the request succeeded.
https://issues.umd.edu/browse/LIBDRUM-595
=> LIBDRUM-595. Skip checking DOI reservation in DataciteConnector.

dspace/modules/additions/src/main/java/org/dspace/app/util/DCInputSet.java
Some of the Dataset related fields are only set of specific submission workflows. Reversing the string equals check should prevent the NPEs.
https://issues.umd.edu/browse/LIBDRUM-639
=> LIBDRUM-639. Fix NPE due to missing input field.

dspace/config/dspace.cfg
https://issues.umd.edu/browse/LIBDRUM-641
=> LIBDRUM-641. Enable non-ImageMagick thumbnail filters.

.github/workflows/build.yml, dspace-api/src/test/data/dspaceFolder/config/local.cfg, dspace-server-webapp/src/test/data/dspaceFolder/config/spring/api/discovery.xml, dspace/config/dspace.cfg, dspace/config/local.cfg.TEMPLATE, dspace/modules/additions/pom.xml
Fixed failing tests be doing the following:
1) Added "assetstore" configuration to the
"dspace-api/src/test/data/dspaceFolder/config/local.cfg" file,
so that Spring can properly set up configuration.
2) Restored the the "dspace/config/dspace.cfg" file to the stock
DSpace 7.2.1 configuration (all UMD modifications to the file were moved
to the "dspace/config/local.cfg.TEMPLATE" file).
3) Added the stock DSpace 7.2.1 "discovery.xml" file to the
"dspace-server-webapp/test/data/dsplaceFolder/config/spring/api/" folder,
so that it would be used by the tests, instead of the UMD-customized
version in "dspace/config/spring/api/discovery.xml".
4) In the "dspace/modules/additions/pom.xml" file, excluded javax.servlet:servlet-api v2.3
from the "casclient" dependency, as it could end up in classpath …
=> LIBDRUM-655. Modifications to fix failing tests

dspace/config/modules/authentication.cfg
The list in the dspace.cfg was appending to the list in the authentication.cfg instead of replacing it, causing the PasswordAuthenticator to be listed twice in the list of authentication methods.
https://issues.umd.edu/browse/LIBDRUM-653
=> LIBDRUM-653. Disabled the default password authenticator.

Dockerfile.dev-additions
https://issues.umd.edu/browse/LIBDRUM-673
=> LIBDRUM-673. Fix DSpace7 quick build missing classes.

dspace/bin/start-handle-server-fg, dspace/solr/Dockerfile
DSpace 7 expects to be using Solr v8, so updating the
dspace/solr/Dockerfile to use a stock Solr v8.11 image, as used by
the stock DSpace 7 installation (see "docker-compose.yml" file in
the project root.
Also, the Kubernetes configuration is expecting a
"start-handle-server-fg" script to exist for starting the Handler server
in the foreground, so added the file, using the same file from
MDSOAR for guidance.
https://issues.umd.edu/browse/LIBDRUM-674
=> LIBDRUM-674. Update Solr/Add handle-server script

Dockerfile.ant
Replaced "wget" command with the equivalent "curl" command, as "wget"
no longer appears to be provided by default by the upstream base Docker
image.
https://issues.umd.edu/browse/LIBDRUM-687
=> LIBDRUM-687. Replaced "wget" with "curl" when building "Dockerfile.ant"

dspace/modules/additions/pom.xml
In the "dspace-api/pom.xml" file, the Jetty dependencies for the
"cnri-servlet-container" (the CNRI Handle Server) are excluded because
they conflict with Jetty versions provided by DSpace.
In DSpace 7.3, the Jetty dependencies used by the
"cnri-servlet-container" are still excluded, but no other DSpace
dependency includes the Jetty dependencies as "compile" dependencies
(they are included as "test" dependencies, which does not get them
included in the the final assembly package).
To ensure that the CNRI Handle Server has the necessary dependencies,
adding them as explicit dependencies (using the DSpace Jetty version)
to the "dspace/modules/additions/pom.xml" file.
The need for these dependencies should be re-evaluated when new DSpace
releases are made. …
=> LIBDRUM-695. Ensure CNRI Handle server has necessary dependencies

dspace/config/item-submission.xml, dspace/config/submission-forms.xml
Customized the submission form for default submissions:
* Made "Author" field required
* Added "Advisor" field
Note: The "file upload required" and "date.issued required" specification
for this issue are DSpace 7 defaults ("date.issued" requires at least a "year"
to be entered), and so required no modifications.
This pull request also has changes from LIBDRUM-696, where all UMD
customizations were commented out of the "dspace/config/item-submission.xml"
file, as the related Java classes have not yet been updated for DSpace 7.
https://issues.umd.edu/browse/LIBDRUM-675
=> LIBDRUM-675. Customize default submission fields

dspace/config/item-submission.xml, dspace/config/spring/api/access-conditions.xml, dspace/config/submission-forms.xml
Added custom workflow for the "Minority Heath and Health
Equity Archive" collection, based on the workflow in DSpace 6.
The major changes are:
* File uploads are optional
* An "External Link" field has been added.
Current implementation only utilitizes DSpace 7 configuration
options, and does not attempt to create new input fields or
otherwise change the behavior of the Angular front-end.
This implementation has the following limitations (compared to
DSpace 6):
* The "upload" and "license" fields are always shown, and the
"license" must be accepted even if no file is uploaded.
* The "External Link" validation is performed using a regex
expression, which is currently not as flexible as the DSpace 6
equivalent (which appears to use the browser's "url" input type
validation). Currently the …
=> LIBDRUM-684. MHHEA collection custom workflow

dspace/modules/additions/src/main/java/edu/umd/lib/dspace/authenticate/impl/Ldap.java, dspace/modules/server/src/main/java/org/dspace/app/rest/model/LdapRest.java, dspace/modules/server/src/main/java/org/dspace/app/rest/repository/EPersonLdapLinkRepository.java
Modified "Ldap" class and associated classes to return all the Units an EPerson matches based on their LDAP criteria, separating them into "matched" (a Unit with that name exists in DSpace) and "unmatched" (a Unit with that name does not exist in DSpace).
https://issues.umd.edu/browse/LIBDRUM-669
* First, ...
* Second, ...
**Include guidance for how to test or review your PR.** This may include: steps …
=> LIBDRUM-669. Modified LDAP to return matched/unmatch Units

dspace/modules/additions/src/main/resources/Messages.properties, dspace/modules/server/src/main/java/org/dspace/app/rest/authorization/impl/DeleteFeature.java, dspace/modules/server/src/main/java/org/dspace/app/rest/repository/UnitRestRepository.java
Some small tweaks were needed to the DSpace back-end code to fix some issues discovered when working in the front-end:
* Moved "dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/DeleteFeature.java" to "dspace/modules/server", in order to enable Units to be deleted.
* Fixed setting of the "Faculty Only" flag
* Provided message for front-end when a unit name is not provided.
https://issues.umd.edu/browse/LIBDRUM-676
=> LIBDRUM-676. Implement "Unit" front-end

dspace/config/emails/duplicate_title, dspace/config/emails/etd_collections, dspace/docs/Drum7DockerDevelopmentEnvironment.md, dspace/modules/additions/src/main/java/edu/umd/lib/dspace/app/EtdLoader.java
DSpace 7 uses the Apache Velocity template engine,
so updates the following email template files to use
Apache Velocity syntax, instead of the Java MessageFormat
syntax:
* dspace/config/emails/duplicate_title
* dspace/config/emails/etd_collections
Also modified the "dspace/modules/additions/src/main/java/edu/umd/lib/dspace/app/EtdLoader.java" file
to provide a "Duplicate title" message in the script output, and provided information in the "dspace/docs/Drum7DockerDevelopmentEnvironment.md" file on setting up the development Docker images to
enable them to run the scripts and capture the email output.
https://issues.umd.edu/browse/LIBDRUM-710
=> LIBDRUM-710. Fix ETD Loader email templates

dspace/config/local.cfg.EXAMPLE, dspace/config/spring/api/workflow-actions.xml, dspace/config/spring/api/workflow.xml, dspace/config/submission-forms.xml, dspace/modules/additions/src/main/java/edu/umd/lib/dspace/xmlworkflow/state/actions/DataCommunityCollectionMappingAction.java, dspace/modules/additions/src/test/data/dspaceFolder/config/spring/api/workflow-actions.xml, dspace/modules/additions/src/test/data/dspaceFolder/config/spring/api/workflow.xml, dspace/modules/additions/src/test/java/org/dspace/xmlworkflow/state/actions/DataCommunityCollectionMappingIT.java
Uses the DSpace 7 "type-bind" functionality to dynamically
modify the submission form to display different
fields (and different labels/hints for fields), based on whether
or not the "Type" field for the item is "Dataset" or "Software".
Also added a workflow action to map the item to the collections
in the "UMD Data Community" community (determined by
the "data.community.handle" property in the "dspace/config/local.cfg"
file), if the type is "Dataset" or "Software".
https://umd-dit.atlassian.net/browse/LIBDRUM-682
=> LIBDRUM-682. Implement Data Community submission form/workflow

Dockerfile.dev-additions, dspace/docs/DrumEmbargoAndAccessRestrictions.md, dspace/modules/server/src/main/java/org/dspace/app/rest/converter/BitstreamConverter.java, dspace/modules/server/src/main/java/org/dspace/app/rest/model/BitstreamRest.java, dspace/modules/server/src/test/java/org/dspace/app/rest/converter/BitstreamConverterIT.java
Modified the "Dockerfile.dev-additions" to add the "csh" and Perl
dependencies used by the "load-etd"/"load-etd-nightly" scripts, to
simplify testing/development of ETD loader functionality. These
libraries are loaded by the "Dockerfile" used for production, so this
makes the development environment a little more similar to production.
Added an "embargoRestriction" field to the  "BitstreamRest" object
passed between the back-end and frontend. The field is a simple string
that contains:
* "NONE" - no embargo (or embargo on item has been lifted)
* "FOREVER" - the embargo never ends
* A date (in yyyy-MM-dd) format, indicating the embargo lift date
Modified the "BitstreamConverter" to populate the "embargoRestriction"
field, based on any "ETD Embargo" resource policies on the bitstream.
Added …
=> LIBDRUM-678. Embargo policy updates

dspace/config/spring/api/discovery.xml
Following the instructions in
https://wiki.lyrasis.org/display/DSDOC7x/Discovery
suppressed the display of the "Has files" search filter in the public "Search" interface by commenting out the
"searchFilterContentInOriginalBundle" bean.
Note: The "Has files" search filter is still present in the "Admin Search", because it seemed like it might still be useful to admins.
https://umd-dit.atlassian.net/browse/LIBDRUM-739
=> LIBDRUM-739. Suppressed "Has files" search filter in public interface

dspace/config/spring/api/access-conditions.xml
Displayed the ability of a user to set an embargo (access restriction) on an uploaded file in the submission form by removing all of the access restriction options in the "access-conditions.xml" file.
This was done in accordance with the instructions in the DSpace 7 documentation:
https://wiki.lyrasis.org/display/DSDOC7x/Submission+User+Interface#SubmissionUserInterface-Modifyingaccessconditions(embargo,etc.)presentedforBitstreams
> options (Required, but can be empty): list of all
> "AccessConditionOption" beans to enable. This list will be shown to
> the user to let them select which access restrictions to place on each
> bitstream. NOTE: To disable the ability to select bitstream access
> restrictions, comment out all <ref> tags to create an empty list of
> options. …
=> LIBDRUM-747. Disabled embargo functionality on submission form.

dspace/config/local.cfg.EXAMPLE, dspace/modules/server/src/main/java/org/dspace/app/rest/security/UsageReportRestPermissionEvaluatorPlugin.java
Added "usage-statistics.authorization.admin.usage" property to "dspace/config/local.cfg.EXAMPLE" to override the setting in "dspace/config/modules/usage-statistics.cfg", so that the "Statistics" menu entry is only shown for admins (i.e., suppressed for non-admins).
https://umd-dit.atlassian.net/browse/LIBDRUM-738
=> LIBDRUM-738. Suppress "Statistics" menu entry for non-admins

dspace/config/local.cfg.EXAMPLE, dspace/docs/DrumWufooFeedback.md, dspace/modules/server/src/main/java/org/dspace/app/rest/WufooFeedbackDTO.java, dspace/modules/server/src/main/java/org/dspace/app/rest/WufooFeedbackRestController.java
Added a "wufoo-feedback" REST endpoint to construct the Wufoo form URL that the Angular browser should redirect the user to when providing feedback,
The controller class pre-populates the URL with form field defaults, using query parameters as described in the Wufoo "URL Modifications" page (https://help.wufoo.com/articles/en_US/kb/URL-Modifications).
An additional configuration parameter "wufoo.feedback.formUrl" was added to the "local.cfg.EXAMPLE" file, which is the base URL of the Wufoo form redirect.
https://umd-dit.atlassian.net/browse/LIBDRUM-748
Please add a more detailed …
=> LIBDRUM-748. Implementation of "wufoo-feedback" REST endpoint

dspace/config/local.cfg.EXAMPLE, dspace/docs/CASAuthentication.md, dspace/modules/additions/src/main/java/edu/umd/lib/dspace/authenticate/impl/LdapServiceImpl.java, dspace/modules/additions/src/main/java/org/dspace/authenticate/CASAuthentication.java, dspace/modules/additions/src/test/java/org/dspace/authenticate/CASAuthenticationTest.java, dspace/modules/additions/src/test/java/org/dspace/authenticate/impl/LdapServiceImplTest.java
Modified "getSpecialGroups" method in "CASAuthentication" to support
populating special groups for impersonated users.
Since the "getSpecialGroups" method is called for every HTTP request,
which for impersonated users may require an LDAP search, modified
the LdapServiceImpl class to cache LDAP results for 5 minutes, to
limit the number of actual calls to the server.
Refactored the code to enable testing.
Added a "drum.ldap.cacheTimeout" parameter to "local.cfg.EXAMPLE"
to control the LdapServiceImpl cache timeout.
https://umd-dit.atlassian.net/browse/LIBDRUM-769
=> LIBDRUM-769. Add special groups for impersonated users

README-DRUM.md
Updated the "README-DRUM.md" for DSpace 7:
* Removed links to documents that are no longer included in the repository
* Rewrote "Building Images for K8s Deployment" instructions to use Kubernetes "build" namespace. This is needed because "arm64"-based Apple laptops can not build the "amd64" images used by Kubernetes
https://umd-dit.atlassian.net/browse/LIBDRUM-790
* First, ...
* Second, ...
**Include …
=> LIBDRUM-790. Updated "README-DRUM.md" for DSpace 7

dspace/src/main/docker/dspace-postgres-pgcrypto/Dockerfile
The latest Postgres 12 version, Postgres 12.15, appears to have some sort of issue with populating the database from downloaded sample data at startup.
Instead of processing the Postgres dump, the following is in the log:
```
server started
CREATE DATABASE
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/mdsoar.sql
SET
SET
SET
SET
SET
set_config
------------
(1 row)
```
The existing steps work correctly with Postgres 12.14, so pinning to that version until a deeper investigation can be performed (or the problem simply corrects itself in the next version).
https://umd-dit.atlassian.net/browse/LIBDRUM-802
=> LIBDRUM-802. Pin Postgres version to 12.14

dspace/config/local.cfg.EXAMPLE, dspace/docs/DrumFeatures.md
Modified the "local.cfg.EXAMPLE" file to increase the maximum upload file size, based on guidance from Terry Owen:
```
... upper limit for a single file is 2GB and 15GB for a record with
multiple files.
```
https://umd-dit.atlassian.net/browse/LIBDRUM-811
=> LIBDRUM-811. Increase the maximum allowed upload file size

dspace/config/local.cfg.EXAMPLE, dspace/docs/DrumFeatures.md
The "By Subject Category" browse category was returning inconsistent results so it was disabled using the configuration property indicated in https://wiki.lyrasis.org/display/DSDOC7x/Configuration+Reference#ConfigurationReference-HierarchicalBrowseIndexes
The other browse options -- "By Issue Date", "By Author", "By Title", and "By Subject" remain in place.
https://umd-dit.atlassian.net/browse/LIBDRUM-844
=> LIBDRUM-844. Disable "By Subject Category" Browse option

dspace/config/crosswalks/DIM2UmdDataCite.xsl, dspace/docs/DrumDOI.md
Incorporated the DataCite Schema 4.5 changes made in DSpace 7.6.2 to the stock "DIM2DataCite.xsl" file
into the "DIM2UmdDataCite.xsl" while preserving UMD customizations.
https://umd-dit.atlassian.net/browse/LIBDRUM-866
=> LIBDRUM-866. Updated DIM2UmdDataCite.xsl for DataCite Schema 4.5

dspace/config/item-submission.xml, dspace/config/submission-forms.xml, dspace/docs/DrumEmbargoAndAccessRestrictions.md, dspace/docs/DrumFeatures.md, dspace/docs/DrumSubmissionForms.md
For the default submission form, created a "Submission Type" step ("umdType") and associated form to enable the "Equitable Access" field to be dynamically displayed/hidden based on whether "Article" was chosen in the "Type" dropdown.
This also required creating a separate "Submission Type" step ("mhheaType") and associated form to display the "Type" field without the "Equitable Access" field, since MHHEA submissions are never use the "Equitable Access" mapping.
Splitting the “Type” field into a separate form step was is necessary, because in the “Minority Health and Health Equity Archive” submission process, the “Equitable Access” field should not be displayed on MHHEA submissions (even it “Article” is selected). DSpace does not provide the functionality to display/hide fields on a …
=> LIBDRUM-876. Modifications to the DRUM Submission Form

.gitignore, README-DRUM.md, dspace/config/local.cfg.EXAMPLE, dspace/docs/DockerDevelopmentEnvironment.md, dspace/docs/DrumConfigurationCustomization.md, dspace/docs/DrumDBRestore.md, postgres-init/README.md, postgres-init/pg_restore.sh
Made the local development setup more consistent with MD-SOAR:
* Renamed "dspace/docs/Drum7DockerDevelopmentEnvironment.md" to "dspace/docs/DockerDevelopmentEnvironment.md"
* Renamed the "postgres-init/pg_restore_drum.sh" script to "postgres-init/pg_restore.sh" and modify it to use the "POSTGRES_DB" environment variable, instead of hard-coding the database
* Updated the documentation to reflect the renaming of the "pg_restore.sh" script
* Added information to the "postgres-init/README.md" on verifying that a database dump from Kubernetes is a complete snapshot
* Removed UMD-customized Creative Commons license settings in “dspace/config/local.cfg.EXAMPLE”, because these settings are now in the stock “dspace/config/dspace.cfg” file.
https://umd-dit.atlassian.net/browse/LIBDRUM-889
=> LIBDRUM-889. Make DRUM local dev setup more consistent with MD-SOAR

dspace/docs/DrumTestPlan.md
Added a DRUM Test Plan document to verify as many UMD customizations and other concerns (such as read-only containers) as feasible.
This plan is not intended to be exhaustive, instead it is designed to provide basic assurance that the UMD customizations are in place, and guard against regressions.
https://umd-dit.atlassian.net/browse/LIBDRUM-897
=> LIBDRUM-897. Initial DRUM Test Plan document

dspace-api/pom.xml, dspace/docs/DrumLogging.md, dspace/modules/server-boot/src/main/java/org/dspace/app/ServerBootApplication.java, dspace/modules/server-boot/src/main/java/org/dspace/app/UmdTomcatWebServerFactoryCustomizer.java, pom.xml
Added the "UmdTomcatWebServerFactoryCustomizer" class to configure the Spring Boot embedded Tomcat server with a JSON-formatting logger that can be activated by a custom
"umd.server.tomcat.accesslog.json.enabled" property.
The stock DSpace “ServerBootApplication.java” file was modified to import the “UmdTomcatWebServerFactoryCustomizer” class.
Added "log4j-layout-template-json" dependency to the "server-boot/pom.xml" file to provide necessary JSON support.
https://umd-dit.atlassian.net/browse/LIBDRUM-901
=> LIBDRUM-901. Provide JSON logging configuration for Kubernetes

dspace/docs/DrumLogging.md
Reorganized the "dspace/docs/DrumLogging.md" document and added information about Solr logging in Kubernetes.
https://umd-dit.atlassian.net/browse/LIBDRUM-900
=> LIBDRUM-900. Added information about Solr logging to "DrumLogging.md"

dspace/config/crosswalks/DIM2UmdDataCite.xsl
Incorporate change from DSpace Pull Request 9796 to rewrite "xml:lang" attributes such as "en_US" to the DataCite required "en-US", as per https://www.w3.org/International/articles/language-tags/#region
https://umd-dit.atlassian.net/browse/LIBDRUM-908
=> LIBDRUM-908. xml:lang underscore fix

dspace/modules/additions/src/main/java/edu/umd/lib/dspace/app/EtdLoader.java
In DSpace 7.6.2 changes were made to the
“dspace-api/src/main/java/org/dspace/authorize/ResourcePolicyServiceImpl.java” class, in which the “create” method was modified to include “EPerson” and “Group” parameters.
When originally updated for DSpace 7.6.2, the DRUM code set these parameters were set to “null” to satisfy the compiler (as the proper group was subsequently set using a “setGroup” method), but this ran afoul of the parameter checking in the “create” method, resulting in the error.
Corrected the issue by supplying the proper Group to the “create” method, and removed the subsequent “setGroup” calls, as they were no longer needed.
https://umd-dit.atlassian.net/browse/LIBDRUM-907
=> LIBDRUM-907. Fix ETD loader resource policy for embargoed bitstreams

docker-compose.yml, dspace/docs/DockerDevelopmentEnvironment.md
In DSpace 7.6.2, the back-end was run using the Tomcat “catalina.sh” script, which automatically included the “JPDA_OPTS” environment variable, if present in the shell.
With the switch to using a Spring Boot embedded Tomcat server, the Tomcat server is started by a “java”  command, instead of the “catalina.sh” script.
Modified the “docker-compose.yml“ to use the “JPDA_OPTS” environment variable when starting the DRUM back-end, i.e. changed:
```yaml
entrypoint:
...
java -jar /dspace/webapps/server-boot.jar --dspace.dir=/dspace
```
to
```yaml
entrypoint:
...
java $${JPDA_OPTS} -jar /dspace/webapps/server-boot.jar --dspace.dir=/dspace
```
The use of the ${{...} was suggested by https://stackoverflow.com/a/65564161
Updated the “DockerDevelopmentEnvironment.md” document to reference the …
=> LIBDRUM-915. Updated docker-compose.yml to support VS Code debugging

dspace/docs/DrumDOI.md, dspace/modules/additions/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java, dspace/modules/additions/src/test/java/org/dspace/identifier/doi/DOIOrganiserTest.java
Modifies the "register-all" command in DOIOrganiser to delete any DOIs in a "TO_BE_REGISTERED" state that does not have an associated item ("dspace_object" in the "doi" Postgres table is null).
This is necessary because DRUM generates a DOI when an item is created, but if the item is deleted before the DOI is registered with DataCite, a NullPointerException is thrown.
Added "DOIOrganiserTest.java" to verify operation of the "purgeEmptyDOIsWithStatus" method.
Added information about this change to "DrumDOI.md" documentation.
https://umd-dit.atlassian.net/browse/LIBDRUM-916
=> LIBDRUM-916. Purge DOIs with no associated bitstream before registration

dspace-api/src/main/java/org/dspace/storage/bitstore/BitstreamStorageServiceImpl.java, dspace-api/src/main/java/org/dspace/storage/bitstore/DSBitStoreService.java, dspace/docs/DrumFeatures.md
Modified the stock DSpace bitstore migration code to skip bitstreams that are not present in the assetstore.
While not needed for production, the ability to skip bitstreams is needed for the "sandbox", "test" and "qa" DRUM migrations, as these instances have production database snapshots, but not all of the production bitstreams (the stock DSpace migration code fails with an error if any bitstream is missing).
The changes in this commit can be removed when the AWS S3 migration is complete.
https://umd-dit.atlassian.net/browse/LIBDRUM-937
=> LIBDRUM-937. Modify bitstore migration to skip missing files

dspace/config/spring/api/bitstore.xml
In "bitstore.xml" added an additional assetstore (assetstore "5") as an AWS S3 assetstore.
In order to use it for new items, DRUM must be configured to use assetstore "5" as the primary assetstore.
Note: Since the "local.cfg.EXAMPLE" file defaults to using assetstore "0", the local development environment should be unaffected by this change.
https://umd-dit.atlassian.net/browse/LIBDEVOPS-1754
=> LIBDEVOPS-1754. Configure AWS S3 assetstore

Dockerfile, Dockerfile.dev
Modified the “Dockerfile” file to include the “openssh-client” as part of the apt-get update command used in generating the Docker image.
Also updated the “Dockerfile.dev” file for consistency with the “Dockerfile”.
The “Dockerfile.dev-additions” file, used in local development was not modified, because it did not seem to be necessary (the packages can be added as needed by developers).
https://umd-dit.atlassian.net/browse/LIBDRUM-940
=> LIBDRUM-940. Added "openssh-client" to DRUM Docker image

dspace-server-webapp/src/main/java/org/dspace/app/rest/RootRestResourceController.java, dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/RootConverter.java, dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RootRestRepository.java, dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/Utils.java, dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthorizationRestRepositoryIT.java, dspace-server-webapp/src/test/java/org/dspace/app/rest/converter/RootConverterTest.java, dspace/config/dspace.cfg, dspace/config/local.cfg.EXAMPLE
Back-port of "ssrBaseUrl" functionality from
DSpace pull request 10374
Implements the ability for Angular Universal to
communicate directly with the DRUM back-end
pod, instead of going through the ingress.
This change was needed for the AWS migration.
https://umd-dit.atlassian.net/browse/LIBDRUM-943
=> LIBDRUM-943. Back-port of DSpace 7.6.3 "ssrBaseUrl" functionality

pom.xml
Updated Spring Boot embedded Tomcat version to v10.1.39 to mitigate CVE-2025-24813.
This change is based on the "patch.diff" file provided on the "dspace-tech" mailing list in a March 18, 2025 email from mrwerdo331@gmail.com.
This customization can be removed when DRUM is upgraded to a DSpace version that uses a Tomcat no longer affected by the CVE.
https://umd-dit.atlassian.net/browse/LIBDRUM-947
=> LIBDRUM-947. Updated Spring Boot embedded Tomcat for CVE-2025-24813

dspace-api/src/main/java/org/dspace/storage/bitstore/BitstreamStorageServiceImpl.java, dspace-api/src/test/java/org/dspace/storage/bitstore/BitstreamStorageServiceImplIT.java
Fixes the checkpointing for bitstore migration by actually committing the changes to the database.
This change was provided to DSpace as DSpace Pull Request 10489. The "UMD Customization" markers can be removed once this pull request is accepted by DSpace.
Replacing "dispatchEvents" with "commit" as testing has shown that this is necessary to ensure that the status of bitstreams is properly updated when the bitstore migration is interrupted.
The provided integration tests fail if bitstreams successfully migrated before the interruption are not properly recordedd in the database as being in the destination assetstore.
https://umd-dit.atlassian.net/browse/LIBDRUM-946
=> LIBDRUM-946. Fix checkpointing for bitstore migration

dspace-api/src/main/java/org/dspace/checker/CheckerCommand.java, dspace-api/src/test/java/org/dspace/checker/ChecksumCheckerIT.java
Fixes the incremental storage of checksums for the "dspace checker" command by actually committing the changes to the database.
This change was provided to DSpace as DSpace Pull Request 10508.
Replacing "uncacheEntity" with "commit" as testing has shown that this is necessary to ensure that the checksums are properly updated when the checjer is interrupted.
The provided integration tests fail if checksums checked before the interruption are not properly recorded in the database. This class is slightly different from the version provided to DSpace for DSpace 9, due to changes in the use of the "java.util.Date" and "java.time.Instant" classes.
https://umd-dit.atlassian.net/browse/LIBDRUM-949
=> LIBDRUM-949. Fix checkpointing for "dspace checker" command
